### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by stanner** [HeySquirrel/tribe#12]

**Comment by allienna** [comment]
Can you add more details?

**Comment by stanner** [comment]
Currently keyboard shortcuts are F1, F2, F3 etc. Make these more usable.  'Tab' should cycle through the panes, 'q' should quit out of Tribe. 'h' brings up help.

**Comment by aesterline** [comment]
@stanner Can you better define what help should look like? Should it pop up in much the same way as the work item detail panel? Should it change based upon the panel that is highlighted? Or should it show all options for all panels?

I finished the `tab` portion of this issue and I realized I wasn't exactly sure what we wanted from the help.

**Comment by stanner** [comment]
I think help should start by being fixed no matter what you're doing with your keyboard. Let's start with a quick description of each panel - can work with you on wording this afternoon. And then, can have all of the keyboard shortcuts listed and what they allow you to do...
