### ISSUE TITLE
Tribe risk <filename> - a new risk assessment for files in your codebase

### ISSUE THREAD

**Issue by stanner** [HeySquirrel/tribe#15]
As a developer, I would like to know how 'risky' a file might be before I start changing it around.  

Risky attributes:
* number of defects
* familiarity of team around the code
* Last time the code / file was touched or changed (more in the past = more risk)
* test failures (integrate with CI tools) 

Command is `tribe risk <filename>`

**Comment by aesterline** [comment]
@stanner What does `familiarity of team around the code` mean? How would we determine that information?

**Comment by stanner** [comment]
that means that no one on the team has touched the code (ever) - or perhaps they know it really well. One thought would be you could optionally provide a list of usernames to the risk command to see if they've made any commits to the code ever.

**Comment by aesterline** [comment]
I added an initial version of the concept to `tribe`. Try `tribe risk <filename>`.
