### ISSUE TITLE
Add homebrew installer for tribe

### ISSUE THREAD

**Issue by aesterline** [HeySquirrel/tribe#16]
Let's make it easy for users to install and get started with `tribe`.

**Comment by aesterline** [comment]
It seems like brew won't allow formula from projects that aren't established. This is the error I get while trying to test the formula I created.

```
tribe:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
Error: 1 problem in 1 formula
```

**Comment by allienna** [comment]
I will take a look on that

Can you assign it to me and add the label `hacktoberfest` please

**Comment by aesterline** [comment]
@allienna Thanks for your help. I think I did what you requested. Please let me know if you need anything else to get started.

**Comment by allienna** [comment]
It's the first time that I do this, I have to read Homebrew documentation

**Comment by aesterline** [comment]
I have never created a private tap either. I am happy to help out if there is any way I can help.

**Comment by aesterline** [comment]
@allienna I figured out how to do this today and got it working. See the `homebrew-tribe` repo for more information.
